# coding: utf-8


# поля, запрашиваемые чере API вызов users.get
VK_USER_FIELDS = [
    'sex',
    'bdate',
    'city',
    'country',
    'online',
    'online_mobile',
    'domain',
    'home_town',
    'has_mobile',
    'contacts',
    'connections',
    'site',
    'education',
    'universities',
    'personal',
    'schools',
    'can_post',
    'can_see_all_posts',
    'can_see_audio',
    'can_write_private_message',
    'status',
    'last_seen',
    'common_count',
    'relation',
    'relatives',
    'counters',
    'screen_name,'
    'maiden_name',
    'timezone',
    'occupation,'
    'activities',
    'interests',
    'music',
    'movies',
    'tv',
    'books',
    'games',
    'about',
    'quotes',
]
